---
config:
  theme: redux-color
---
sequenceDiagram
    actor Власник
    participant Ветеринар
    participant Лабораторія
    participant Система
    Власник->>Система: записатисьНаВакцинацію(дата)
    activate Система
    Система-->>Власник: підтвердження запису
    deactivate Система
    Власник->>Ветеринар: прийти на прийом
    activate Ветеринар
    Ветеринар->>Система: оглянути(тварина)
    Ветеринар->>Система: внестиЩеплення(тварина)
    deactivate Ветеринар
    Ветеринар->>Лабораторія: надіслати аналіз
    activate Лабораторія
    Лабораторія->>Система: опублікуватиРезультати()
    deactivate Лабораторія
    Власник->>Система: оплатити(сума)
    activate Система
    Система-->>Власник: видати аналізи
    deactivate Система
